import turtle

tina = turtle.Turtle()
tina.shape('turtle')

tina.penup()
tina.goto(30, -150)
tina.pendown()
tina.circle(130)
tina.penup()
tina.goto(0, 0)
tina.pendown()
tina.circle(20)
tina.circle(10)
tina.penup()
tina.forward(60)
tina.right(45)
tina.pendown()
tina.circle(30)
tina.circle(10)
tina.penup()
tina.right(90)
tina.forward(90)
tina.pendown()
tina.circle(40)
tina.penup()
tina.goto(25, -25)

input('press any key ...')
